<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="Imtiaz" ignored="0" name="Facebook App Test Cases" tests="3" failures="2" timestamp="19 Apr 2019 06:52:58 GMT" time="93.234" errors="0">
  <testcase name="doLogin" time="0.016" classname="com.pom.testcases.LoginTest">
    <skipped/>
  </testcase> <!-- doLogin -->
  <testcase name="doLogin" time="47.852" classname="com.pom.testcases.LoginTest">
    <failure type="java.lang.AssertionError" message="Login Not Successful">
      <![CDATA[java.lang.AssertionError: Login Not Successful
	at com.pom.testcases.basetest.BaseTest.reportFailure(BaseTest.java:77)
	at com.pom.testcases.LoginTest.doLogin(LoginTest.java:49)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- doLogin -->
  <testcase name="changePasswordTest" time="44.769" classname="com.pom.testcases.ChangePasswordTest">
    <failure type="java.lang.AssertionError" message="Could not Login">
      <![CDATA[java.lang.AssertionError: Could not Login
	at com.pom.testcases.basetest.BaseTest.reportFailure(BaseTest.java:77)
	at com.pom.testcases.ChangePasswordTest.changePasswordTest(ChangePasswordTest.java:47)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- changePasswordTest -->
</testsuite> <!-- Facebook App Test Cases -->
